# Generated by Django 4.0.3 on 2022-03-27 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booktakingdatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booknumber', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('takendate', models.DateTimeField(default=datetime.datetime.now)),
                ('returndate', models.DateTimeField()),
            ],
        ),
    ]
