# Generated by Django 4.0.3 on 2022-03-27 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_department_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department_name',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='course_name',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='subject',
        ),
    ]
