# Generated by Django 4.0.3 on 2022-04-16 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionpool', '0019_delete_question'),
        ('authentication', '0007_delete_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='posts',
        ),
        migrations.RemoveField(
            model_name='quesadmin',
            name='quesadmin_username',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='staff_username',
        ),
        migrations.RemoveField(
            model_name='students',
            name='student_username',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
        migrations.DeleteModel(
            name='department',
        ),
        migrations.DeleteModel(
            name='quesadmin',
        ),
        migrations.DeleteModel(
            name='staffs',
        ),
        migrations.DeleteModel(
            name='students',
        ),
        migrations.DeleteModel(
            name='subject',
        ),
    ]
