# Generated by Django 4.0.3 on 2022-03-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionpool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='department',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_department',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_semester',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_subject',
        ),
        migrations.DeleteModel(
            name='department',
        ),
        migrations.DeleteModel(
            name='semester',
        ),
        migrations.DeleteModel(
            name='subject',
        ),
    ]
