# Generated by Django 4.0.3 on 2022-03-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpool', '0002_remove_semester_department_remove_subject_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(default='nill', max_length=30)),
            ],
        ),
    ]
