# Generated by Django 4.0.3 on 2022-03-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpool', '0003_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=100)),
            ],
        ),
    ]
