# Generated by Django 4.0.3 on 2022-03-26 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionpool', '0004_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionpool.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionpool.semester')),
            ],
        ),
    ]
