# Generated by Django 4.0.3 on 2022-03-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionpool', '0005_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='question',
        ),
    ]
