# Generated by Django 4.0.3 on 2022-03-26 13:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionpool', '0006_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.IntegerField(default=0)),
                ('question_ques', models.CharField(max_length=200)),
                ('question_answer', models.CharField(max_length=200)),
                ('question_quesattach', models.ImageField(upload_to='question/')),
                ('question_answerattach', models.ImageField(upload_to='question/')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('question_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionpool.department')),
                ('question_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionpool.semester')),
                ('question_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionpool.subject')),
            ],
        ),
    ]
