# Generated by Django 4.0.3 on 2022-03-27 21:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_department_subject'),
        ('questionpool', '0010_remove_question_question_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('question_num', models.IntegerField(primary_key=True, serialize=False)),
                ('question_ques', models.CharField(max_length=200)),
                ('question_answer', models.CharField(max_length=200)),
                ('question_quesattach', models.ImageField(upload_to='question/')),
                ('question_answerattach', models.ImageField(upload_to='question/')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('question_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.courses')),
                ('question_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.subject')),
            ],
        ),
    ]
