# Generated by Django 4.0.3 on 2022-03-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionpool', '0012_alter_question_question_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_course',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_subject',
        ),
    ]
