# Generated by Django 4.0.3 on 2022-03-28 17:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0007_delete_courses'),
        ('questionpool', '0016_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('question_num', models.AutoField(primary_key=True, serialize=False)),
                ('question_ques', models.CharField(max_length=200)),
                ('question_answer', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('question_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.department')),
                ('question_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.subject')),
            ],
        ),
    ]
