# Generated by Django 4.0.3 on 2022-03-28 17:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionpool', '0017_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_ques',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
